Added parse
gherking/gherkin-io pull request #9
Opened 2023-07-28 16:04 UTC by szikszail

2023-07-29 17:17 UTC, haikyuu commented
Very nice :) I wasn't expecting to use this in Monday 👍 
Thank you

2023-07-30 13:06 UTC, MonikaLaszlo requested changes

2023-07-30 13:06 UTC, MonikaLaszlo commented on package.json
>    "description": "Tool to read/write GHerkin feature files and work with Gherking AST",
```suggestion
  "description": "Tool to read/write Gherkin feature files and work with Gherking AST",
```

2023-07-30 13:07 UTC, MonikaLaszlo approved these changes

2023-07-30 13:08 UTC, merged